name: CI

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

env:
  RAILS_ENV: test
  DATABASE_URL: postgresql://postgres:@localhost/test
  DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true

jobs:
  rubocop:
    uses: theforeman/actions/.github/workflows/rubocop.yml@v0
    with:
      command: bundle exec rubocop --parallel --format github
  
  test:
    name: Ruby
    needs: rubocop
    strategy:
      fail-fast: false
      matrix:
        foreman-core-branch:
          - 3.7-stable
          - 3.8-stable
          - 3.9-stable
          - develop
    uses: theforeman/actions/.github/workflows/foreman_plugin.yml@v0
    with:
      plugin: foreman_omaha
      foreman_version: ${{ matrix.foreman-core-branch }}
